services:
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: npm run start:debug
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    ports: ["3306:3306"]
    networks:
      - webnet
networks:
  webnet:
