const {
  DATABASE_HOST = "localhost",
  DATABASE_PORT = 3306,
  DATABASE_USERNAME = "test",
  DATABASE_PASSWORD = "test",
  DATABASE_NAME = "movies",
  SERVER_PORT = 3000,
} = process.env;

export {
  DATABASE_HOST,
  DATABASE_PORT,
  DATABASE_USERNAME,
  DATABASE_PASSWORD,
  DATABASE_NAME,
  SERVER_PORT,
};
