const {
  DATABASE_HOST = "localhost",
  DATABASE_PORT = 3306,
  DATABASE_USERNAME = "test",
  DATABASE_PASSWORD = "test",
  DATABASE_NAME = "movies",
  DEFAULT_PAGE = 1,
  DEFAULT_PER_PAGE = 50,
  MAXIMUM_PER_PAGE = 200,
  SERVER_PORT = 3000,
} = process.env;

export {
  DATABASE_HOST,
  DATABASE_PORT,
  DATABASE_USERNAME,
  DATABASE_PASSWORD,
  DATABASE_NAME,
  DEFAULT_PAGE,
  DEFAULT_PER_PAGE,
  MAXIMUM_PER_PAGE,
  SERVER_PORT,
};
